# Generated by Django 5.0 on 2023-12-29 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0002_remove_cycle_name_cycle_action_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='problem_description',
            field=models.CharField(default='', max_length=500),
        ),
    ]
